### ISSUE TITLE
This is awesome and have a suggestion

### ISSUE THREAD

**Issue by hamiltoncj** [antoniocarlon/SplitPolygonShowingAreas#2]
This is a capability that I have really wanted to have and had been thinking about coding it myself. The suggestion I have, that would make it perfect for my use, would be to add the ability to edit your splitting line, to add and remove nodes once it is drawn before splitting. Also the ability to escape and not do the split. You may already be planning this so forgive me if I am jumping in too soon with this suggestion. 

On the other hand the standard QGIS editing tools (with topological editing enabled) may be all that is necessary once the split has been made.

I am excited that you are doing this plugin.

Calvin

**Comment by antoniocarlon** [comment]
Thank you for your support!
I'm thinking about improving the tool (or creating a new one with a better name ;)) to add some functionalities such as adding, removing and moving (displacing) vertices (and even segments).
Thanks again!
Antonio

**Comment by antoniocarlon** [comment]
I have updated the plugin to allow moving the vertices of the cutting line before splitting. Take a look at the new version (0.6).
Regards,
Antonio

**Comment by hamiltoncj** [comment]
I just checked back and it looks like you are at version 11. I am getting an error in trying to install it. I think the problem is because you renamed it. It is installing in the folder SplitPolygonShowingAreas, but if it is renamed to SplitFeaturesOnSteroidsPlugin it will at least load, however when I run QGIS none of the menu items are enabled except Help.

Thanks

**Comment by antoniocarlon** [comment]
I have installed version 0.1 and successfully upgraded to 0.11. Could you try manually uninstalling it and installing last version?
I promise you won't be disappointed :)

**Comment by hamiltoncj** [comment]
Excellent. After manually uninstalling and then reinstalling, everything worked properly. I like it!!!!
