### ISSUE TITLE
Toolbar buttons are greyed out

### ISSUE THREAD

**Issue by dataflownow** [antoniocarlon/SplitPolygonShowingAreas#3]
I'd like to use this plugin.  I have a large shape I'm trying to split/divide.  I select the layer, and toggle into the edit mode, but nothing I do will enable the Split Features On Steriods toolbar buttons.   They are always greyed out. :(
I'm using QGIS 2.18.13 on Windows 10.

**Comment by dataflownow** [comment]
OK.  I figured it out.  It's not enough to select the layer, and be in edit mode, I also have to have the shape *selected* using the selection tool(s).  Awesome!  Thanks!

**Comment by dataflownow** [comment]
Well, maybe I didn't figure it out after all.  When I created a vector layer and added a simple shape to it.  I could select it and use Split Features On Steroids just fine.  But when I selected a layer with a complex shape that I imported that has thousands of nodes, the Split Features On Steroids toolbar button remains disabled/greyed out.  :(

**Comment by antoniocarlon** [comment]
As you say the conditions for _Split Features On Steroids_ to be enabled are having a layer selected, having a feature selected and being in edit mode, so this may be a bug.

Could you share the feature that is causing this (a shapefile for example)?

**Comment by dataflownow** [comment]
I ran Vector > Geometry Tools > Check validity on my shape, and found an error.  Once that had been corrected, the Split Features On Steroids button was enabled when I selected the shape.

Now, I can use the Split Features On Steroids button to draw cutting lines, but I can't figure out how to make the actual split/cut.

**Comment by antoniocarlon** [comment]
The _Split Features On Steroids_ plugin works like the default _Split Features_ tool from QGIS. Thus, to split a feature you need to draw a cutting line and then right click to make the actual cut.
Please let me know if it's working.

**Comment by dataflownow** [comment]
I tried right clicking, but my shape didn't split.  The line just disappeared.

**Comment by antoniocarlon** [comment]
Can the default _Split Features_ tool from QGIS split the feature or the cutting line is also dissapearing when using the default tool?

**Comment by dataflownow** [comment]
I am able to use the default Split Features tool from QGIS, and also Split Features On Steroids on some simple shapes that I created.  My problem is with this larger more complex shape that I have imported.  I think the problem is with my shape and not with Split Features On Steroids.  Thanks for your time.

**Comment by marinhow** [comment]
Hello, i am havingthis issue where i created a polygon from a series of gps coordenates and i have to split this polygon into equal areas but in unregulat forms. I sellect the polygon layer and enter editing mode but the toolbar does not become active, what am I doing wrong?

**Comment by antoniocarlon** [comment]
Hi! The workflow is selecting the layer, selecting the feature and then enter in edit mode. The toolbar should be enabled after following these steps.

If it's not working yet, could you please send me the feature that you can't edit?

Thank you!
