### ISSUE TITLE
2.5D Polygon

### ISSUE THREAD

**Issue by JuliaOnn** [antoniocarlon/SplitPolygonShowingAreas#4]
How can I split 2.5D polygons with a z coordinate? Has someone an idea?

**Comment by antoniocarlon** [comment]
The 2.5D effect is just a rendering trick, the underlying polygons are normal 2D polygons that can be cut using this plugin or the default QGIS split tool.

Are you finding any problem doing it?

**Comment by mhoelzner** [comment]
checking for `layer.wkbType() == QgsWkbTypes.Polygon` somehow doesn't work with a polygon containing z-value information, description showing geometry -> Polygon (Polygon25D) 
I fixed it temporary by removing the checks for Polygon and Multipolygon to enable the button, but don't know how to check for future uses with that kind of polygon

**Comment by mhoelzner** [comment]
the button to split a polygon wont be enabled unless the polygon is a
`layer.wkbType` of `QgsWkbTypes.MultiPolygon` or `QgsWkbTypes.Polygon`

to use it with polygons having some sort of z values, additional types have to be checked like
`layer.wkbType` of `QgsWkbTypes.MultiPolygon25D` or `QgsWkbTypes.Polygon25D`

**Comment by antoniocarlon** [comment]
I have uploaded a new version including your changes (https://github.com/antoniocarlon/SplitPolygonShowingAreas/pull/5#pullrequestreview-108196030).

I'll let you know when it's approved and can be downloaded.

Thank you for your contribution!

**Comment by antoniocarlon** [comment]
The new version has been approved and released. @JuliaOnn could you try it to see if it solves your issue?

**Comment by JuliaOnn** [comment]
It works fine! Thank you for editing your feature.
